sonar.projectKey=devops-company
sonar.sources=src
sonar.tests=src
sonar.inclusions=src/**/*.js,src/**/*.jsx,src/**/*.test.js,src/**/*.test.jsx,src/**/*.spec.js,src/**/*.spec.jsx
sonar.test.inclusions=src/**/*.test.js,src/**/*.test.jsx,src/**/*.spec.js,src/**/*.spec.jsx
sonar.exclusions=**/node_modules/**,**/coverage/**,**/public/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8