sonar.projectKey=devops-company
sonar.sources=src
sonar.tests=src
sonar.inclusions=src/**/*.js,src/**/*.jsx
sonar.test.inclusions=src/**/*.test.js,src/**/*.test.jsx,src/**/*.spec.js,src/**/*.spec.jsx
sonar.exclusions=**/node_modules/**,**/public/**,**/coverage/**,**/*.json
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.host.url=http://54.242.68.69:9000
sonar.login=sonar-cred